[package]
name = "neosh"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44.0", features = ["full", "mio"] }
slog = "2.7.0"
slog-async = "2.8.0"
slog-json = "2.6.1"
colored = "3.0.0"
is_executable = "1.0.4"
